name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # e.g., us-east-1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: public.ecr.aws/s8z2n5e0/sample-ruby-app:latest

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy@v1
      with:
        cluster: 
        service: <YOUR_ECS_SERVICE_NAME>
        image: <YOUR_ECR_REGISTRY_URL>/<YOUR_IMAGE_NAME>:latest
